siteTitle = "Правильное питание с доставкой в Оренбурге +7(3532)554544"
siteDescr = "Употребляем в пищу только полезные, натуральные продукты, исключаем вредные продукты "
siteAuthor = "Правильное питание"

siteTelegramUrl = "#"
siteInstaUrl = "https://www.instagram.com/lfoodlife/"
siteFbUrl = "#"
siteVkUrl = "#"
siteEmailUrl = "#"

googleAnalyticsId = ""

linkPrefix = ""